# Generated by Django 4.2.11 on 2024-03-14 20:44

import cloudinary.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Emote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emote_img', cloudinary.models.CloudinaryField(default='placeholder', max_length=255)),
                ('title', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Only alphanumeric characters and hyphens are allowed.', regex='^[a-zA-Z0-9-]+$')])),
                ('category', models.CharField(choices=[('Happy', 'Happy'), ('Sad', 'Sad'), ('Excited', 'Excited'), ('Love', 'Love'), ('Angry', 'Angry'), ('Laughing', 'Laughing'), ('Cry', 'Cry'), ('Surprised', 'Surprised'), ('Confused', 'Confused'), ('Thumbs Up/Down', 'Thumbs Up/Down'), ('Celebration', 'Celebration'), ('Dance', 'Dance'), ('Cool', 'Cool'), ('Cute', 'Cute'), ('Funny', 'Funny'), ('Other', 'Other')], default='Happy', max_length=50)),
                ('upload_date', models.DateTimeField(auto_now=True)),
                ('favourites', models.ManyToManyField(blank=True, default=None, related_name='favourite', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-upload_date'],
            },
        ),
    ]
